name: Flutter CI/CD
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install dependencies
        run: flutter pub get
      - name: Build
        run: flutter build apk
      - name: Test
        run: flutter test
      - name: Send email with APK attachment
          uses: dawidd6/action-send-mail@v3
          with:
            server_port: 465
            secure: true
            server_address: smtp.gmail.com
            username: Kelebernadin00@gmail.com
            password: tiia nmxw sloy pedw
            from: Kelebernadin00@gmail.com
            to: officialbernadin@gmail.com
            subject: "completed successfully!"
            body: "The APK for the ${{ env.BRANCH }} branch has been built and is  attached ."
